## Place read-only configurations in this file.
## To define configurations that can later be overridden through UI/API/CLI, add them to `etc/base.hocon`.
##
## Config precedence order:
##   etc/base.hocon < cluster.hocon < emqx.conf < environment variables
##
## See https://docs.emqx.com/en/enterprise/latest/configuration/configuration.html for more information.
## Configuration full example can be found in etc/examples

node {
  name = "emqx@127.0.0.1"
  cookie = "emqx50elixir"
  data_dir = "data"
}

cluster {
  name = emqxcl
  discovery_strategy = manual
}

dashboard {
    listeners {
        http.bind = 18083
        # https.bind = 18084
        https {
            ssl_options {
                certfile = "${EMQX_ETC_DIR}/certs/cert.pem"
                keyfile = "${EMQX_ETC_DIR}/certs/key.pem"
            }
        }
    }
}

authentication = [
  {
    checks = [
      {
        is_match = [
          "str_eq(username, 'uplink')",
          "regex_match(clientid, '^(MeshtasticPythonMqttProxy-[A-Za-z0-9!_-]+|MeshtasticAppleMqttProxy-[A-Za-z0-9!_-]+|MeshtasticAndroidMqttProxy-[A-Za-z0-9!_-]+|![A-Za-z0-9]+)$')"
        ]
        result = ignore
      },
      {
        is_match = "str_eq(username, 'uplink')"
        result = deny
      },
      {
        is_match = [
          "str_eq(username, 'bridge_meshstuff')",
          "str_eq(clientid, 'meshstuff.bridge-to-flmesh')"
        ]
        result = ignore
      },
      {
        is_match = "str_eq(username, 'bridge_meshstuff')"
        result = deny
      },
      {
        is_match = [
          "str_eq(username, 'bridge_core_mosquitto')",
          "str_eq(clientid, 'core-mosquitto.bridge_to_flmesh')"
        ]
        result = ignore
      },
      {
        is_match = "str_eq(username, 'bridge_core_mosquitto')"
        result = deny
      },
      {
        is_match = [
          "str_eq(username, 'bridge_zgw')",
          "str_eq(clientid, 'zgw.meshtastic_upstream')"
        ]
        result = ignore
      },
      {
        is_match = "str_eq(username, 'bridge_zgw')"
        result = deny
      },
      {
        is_match = [
          "str_eq(username, 'bridge_scmqtt')",
          "str_eq(clientid, 'scmqtt.mqtt_areyoumeshingwith_us')"
        ]
        result = ignore
      },
      {
        is_match = "str_eq(username, 'bridge_scmqtt')"
        result = deny
      }
    ]
    enable = false
    mechanism = cinfo
  },
  {
    backend = built_in_database
    enable = true
    mechanism = password_based
    password_hash_algorithm {
      iterations = 101
      mac_fun = sha512
      name = pbkdf2
    }
    user_id_type = username
  }
]
